name: mte_socketx
description: "A Flutter Plugin for secure WebSocket communication using the Eclypses SocketX protocol."
version: 2.1.0
homepage:

environment:
  sdk: ^3.7.0-138.0.dev
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.eclypses.mte_socketx
        pluginClass: SocketXClientPlugin
      ios:
        pluginClass: SocketXClientPlugin

